/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseTrumpDialog.java
 *
 * Created on 2010-05-14, 16:57:53
 */
package hearts.client.hui;

import hearts.defs.state.CardColor;
import hearts.defs.state.GameConstants;
import hearts.defs.state.IGUIState;
import hearts.state.actions.ChooseTrumpAction;
import java.util.Hashtable;
import javax.swing.JButton;

/**
 *
 * @author szymon
 */
public class ChooseTrumpDialog extends javax.swing.JDialog {

    protected Hashtable<JButton, CardColor> colors =
            new Hashtable<JButton, CardColor>(4);

    IGUIState gui;

    public IGUIState getGui() {
        return gui;
    }

    public void setGui(IGUIState gui) {
        this.gui = gui;
    }

    /** Creates new form ChooseTrumpDialog */
    public ChooseTrumpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        colors.put(clubButton, CardColor.CLUB);
        colors.put(diamondButton, CardColor.DIAMOND);
        colors.put(heartsButton, CardColor.HEART);
        colors.put(spadeButton, CardColor.SPADE);
//        for(JButton b: colors.keySet()) {
//            b.putClientProperty("JComponent.sizeVariant", "large");
//        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        heartsButton = new javax.swing.JButton();
        spadeButton = new javax.swing.JButton();
        diamondButton = new javax.swing.JButton();
        clubButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wybierz atut");
        setMinimumSize(new java.awt.Dimension(300, 150));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        heartsButton.setText("♥");
        heartsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trumpChoosedAction(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        getContentPane().add(heartsButton, gridBagConstraints);

        spadeButton.setText("♠");
        spadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trumpChoosedAction(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        getContentPane().add(spadeButton, gridBagConstraints);

        diamondButton.setText("♦");
        diamondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trumpChoosedAction(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        getContentPane().add(diamondButton, gridBagConstraints);

        clubButton.setText("♣");
        clubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trumpChoosedAction(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        getContentPane().add(clubButton, gridBagConstraints);

        jLabel1.setText("Wybierz atut:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trumpChoosedAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trumpChoosedAction
        CardColor color = colors.get(evt.getSource());
        ChooseTrumpAction chTrump = new ChooseTrumpAction(GameConstants.SERVER);
        chTrump.setTurmp(color);
        gui.getSocket().actionReceived(chTrump);
        this.setVisible(false);
    }//GEN-LAST:event_trumpChoosedAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ChooseTrumpDialog dialog = new ChooseTrumpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clubButton;
    private javax.swing.JButton diamondButton;
    private javax.swing.JButton heartsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton spadeButton;
    // End of variables declaration//GEN-END:variables
}
