/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeckTester.java
 *
 * Created on 2010-05-06, 21:24:51
 */

package hearts.client.hui;

import hearts.client.hui.details.CardIcon;
import hearts.defs.state.CardColor;
import hearts.state.Card;
import hearts.state.exceptions.WrongCardValueException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author szymon
 */
public class DeckTester extends javax.swing.JFrame {

    /** Creates new form DeckTester */
    public DeckTester() {
        initComponents();
        for(CardColor color: CardColor.values()) {
            for(int i = 2; i <= 14; ++i) {
                try {
                    jPanel1.add(new CardIcon(new Card(color, i)));
                } catch (WrongCardValueException ex) {
                    Logger.getLogger(DeckTester.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deck Tester");
        setMinimumSize(new java.awt.Dimension(900, 700));

        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setLayout(new java.awt.GridLayout(4, 13, 5, 5));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeckTester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
