/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gameTable.java
 *
 * Created on 2010-05-06, 19:06:12
 */

package hearts.client.hui;

import hearts.defs.state.IGUIGameTable;
import hearts.defs.state.IGUIPanel.Panel;

/**
 *
 * @author szymon
 */
public class GameTable extends javax.swing.JPanel implements IGUIGameTable {

    /** Creates new form gameTable */
    public GameTable() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        opponentCardsStack1 = new hearts.client.hui.details.OpponentCardsStack();
        opponentCardsStack2 = new hearts.client.hui.details.OpponentCardsStack();
        opponentCardsStack3 = new hearts.client.hui.details.OpponentCardsStack();

        setLayout(new java.awt.GridBagLayout());

        opponentCardsStack1.setVertical(false);

        javax.swing.GroupLayout opponentCardsStack1Layout = new javax.swing.GroupLayout(opponentCardsStack1);
        opponentCardsStack1.setLayout(opponentCardsStack1Layout);
        opponentCardsStack1Layout.setHorizontalGroup(
            opponentCardsStack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        opponentCardsStack1Layout.setVerticalGroup(
            opponentCardsStack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(opponentCardsStack1, gridBagConstraints);

        opponentCardsStack2.setInverted(true);

        javax.swing.GroupLayout opponentCardsStack2Layout = new javax.swing.GroupLayout(opponentCardsStack2);
        opponentCardsStack2.setLayout(opponentCardsStack2Layout);
        opponentCardsStack2Layout.setHorizontalGroup(
            opponentCardsStack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        opponentCardsStack2Layout.setVerticalGroup(
            opponentCardsStack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        add(opponentCardsStack2, gridBagConstraints);

        javax.swing.GroupLayout opponentCardsStack3Layout = new javax.swing.GroupLayout(opponentCardsStack3);
        opponentCardsStack3.setLayout(opponentCardsStack3Layout);
        opponentCardsStack3Layout.setHorizontalGroup(
            opponentCardsStack3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        opponentCardsStack3Layout.setVerticalGroup(
            opponentCardsStack3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        add(opponentCardsStack3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hearts.client.hui.details.OpponentCardsStack opponentCardsStack1;
    private hearts.client.hui.details.OpponentCardsStack opponentCardsStack2;
    private hearts.client.hui.details.OpponentCardsStack opponentCardsStack3;
    // End of variables declaration//GEN-END:variables

    public Panel getPanelType() {
        return Panel.GAME;
    }

}
